import { hostname } from 'node:os'
import type { Device } from '../../protocol/sync'
import { randomHex, randomId } from './identity'
import { SyncHttpError, type SyncTransport, normalizeServerUrl } from './http'
import type { SyncStore } from './store'
import type { SyncCredentials } from './types'
const ENROLLMENT_HTTP_UNAUTHORIZED = 401

export async function recoverEnrollment(store: SyncStore, transport: SyncTransport): Promise<SyncCredentials | undefined> {
  const credentials = store.credentials()
  if (!credentials) return undefined
  try {
    const device = await transport.request<Device>(credentials, '/v1/device')
    if (device.deviceId !== credentials.deviceId) throw new Error('Server returned a different device identity.')
    store.confirm()
    return store.credentials()
  } catch (error) {
    if (!(error instanceof SyncHttpError) || error.status !== ENROLLMENT_HTTP_UNAUTHORIZED || credentials.confirmed) throw error
  }
  const device = await transport.request<Device>(credentials, '/v1/enroll', 'POST', {
    token: credentials.token,
    deviceId: credentials.deviceId,
    secret: credentials.secret,
    name: credentials.name
  })
  if (device.deviceId !== credentials.deviceId) throw new Error('Server returned a different device identity.')
  store.confirm()
  return store.credentials()
}

export async function enrollDevice(store: SyncStore, transport: SyncTransport, url: string, token: string, name = hostname(), allowLoopbackHttp = false) {
  const origin = normalizeServerUrl(url, allowLoopbackHttp)
  const prior = store.credentials()
  if (!prior || prior.url !== origin || (prior.confirmed && token.trim())) {
    if (!/^[0-9a-f]{64}$/.test(token.trim())) throw new Error('Enter the registration token generated by your server.')
    store.saveCredentials({ url: origin, deviceId: randomId(), secret: randomHex(), name, token: token.trim(), confirmed: false })
  } else if (!prior.confirmed && token.trim() && token.trim() !== prior.token) {
    if (!/^[0-9a-f]{64}$/.test(token.trim())) throw new Error('Enter the registration token generated by your server.')
    store.saveCredentials({ ...prior, token: token.trim() })
  }
  return recoverEnrollment(store, transport)
}
