import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, extname, resolve } from 'node:path'
import { parseSync } from 'rolldown/experimental'

function resolveSource(parent, specifier) {
  if (specifier.startsWith('@noble/hashes/')) {
    return resolve('node_modules/@noble/hashes/src', specifier.slice('@noble/hashes/'.length).replace(/\.js$/, '.ts'))
  }
  if (!specifier.startsWith('.')) throw new Error(`Unsupported worker import: ${specifier}`)
  const path = resolve(dirname(parent), specifier)
  return extname(path) ? path : path + '.ts'
}

function declarationNames(node) {
  if (node.type === 'VariableDeclaration') return node.declarations.map((declaration) => declaration.id.name).filter(Boolean)
  return node.id?.name ? [node.id.name] : []
}

async function flattenWorker(entry) {
  const modules = new Map()
  const names = new Set()
  const output = []
  function stripExports(source, body, changes, exported) {
    for (const node of body) {
      const declaration = node.declaration ?? node
      for (const name of declarationNames(declaration)) {
        if (names.has(name)) throw new Error(`Duplicate worker declaration: ${name}`)
        names.add(name)
      }
      if (node.type !== 'ExportNamedDeclaration') continue
      if (node.declaration) {
        exported.push(...declarationNames(node.declaration))
        changes.push([node.start, node.declaration.start, ''])
      } else {
        exported.push(...node.specifiers.map((specifier) => specifier.local.name))
        changes.push([node.start, node.end, ''])
      }
    }
    let flat = source
    for (const [start, end, replacement] of changes.toSorted((left, right) => right[0] - left[0])) {
      flat = flat.slice(0, start) + replacement + flat.slice(end)
    }
    return flat
  }
  async function appendModule(file) {
    if (modules.has(file)) return modules.get(file)
    const source = await readFile(file, 'utf8')
    const parsed = parseSync(file, source)
    if (parsed.errors.length) throw new Error(`Invalid worker source: ${file}`)
    const exported = []
    modules.set(file, exported)
    const changes = []
    for (const node of parsed.program.body) {
      if (node.type !== 'ImportDeclaration' || node.source.value.startsWith('node:')) continue
      const dependency = await appendModule(resolveSource(file, node.source.value))
      const namespace = node.specifiers.find((specifier) => specifier.type === 'ImportNamespaceSpecifier')
      if (namespace) changes.push([node.start, node.end, `const ${namespace.local.name} = { ${dependency.join(', ')} };`])
      else changes.push([node.start, node.end, ''])
    }
    const flat = stripExports(source, parsed.program.body, changes, exported)
    output.push(`// Source: ${file}\n${flat}`)
    return exported
  }
  await appendModule(resolve(entry))
  return '// Generated by scripts/build-workers.mjs. Do not edit.\n' + output.join('\n')
}

// Preserve upstream TypeScript bodies and annotations; Perry workers initialize one module body.
await mkdir('.perry/generated', { recursive: true })
const entries = [['src/desktop/scan/worker.ts', '.perry/generated/scan-worker.ts']]
if (process.argv.includes('--verification')) {
  entries.push(
    ['src/verification/worker.ts', '.perry/generated/verification-worker.ts'],
    ['src/verification/bundle-worker-probe.ts', '.perry/generated/hash-worker.ts'],
    ['src/verification/reader-width.ts', '.perry/generated/reader-width.ts']
  )
}
for (const [input, file] of entries) {
  await writeFile(file, await flattenWorker(input))
}
